### ISSUE TITLE
Pytest failure AttributeError: 'ImageStack' object has no attribute 'shape'

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#2129]
### Summary

Pytest is failing for me locally. Looks like a GPU test that would not be run on github actions

```
FAILED mantidimaging/core/operations/median_filter/test/median_filter_test.py::MedianTest::test_executed_with_nan_1_GPU - AttributeError: 'ImageStack' object has no attribute 'shape'
FAILED mantidimaging/core/operations/median_filter/test/median_filter_test.py::MedianTest::test_executed_no_helper_gpu - AttributeError: 'ImageStack' object has no attribute 'shape'
FAILED mantidimaging/core/operations/test/operations_test.py::OperationsTest::test_operation_works_inplace - AttributeError: 'ImageStack' object has no attribute 'shape'
FAILED mantidimaging/core/gpu/test/gpu_test.py::GPUTest::test_double_is_used_in_cuda_for_float_64_arrays - AttributeError: 'ImageStack' object has no attribute 'shape'
FAILED mantidimaging/core/gpu/test/gpu_test.py::GPUTest::test_numpy_pad_modes_match_scipy_median_modes - AttributeError: 'ImageStack' object has no attribute 'shape'
FAILED mantidimaging/core/gpu/test/gpu_test.py::GPUTest::test_gpu_result_matches_cpu_result_for_different_filter_sizes - AttributeError: 'ImageStack' object has no attribute 'shape'
FAILED mantidimaging/core/gpu/test/gpu_test.py::GPUTest::test_gpu_result_matches_cpu_result_for_larger_images - AttributeError: 'ImageStack' object has no attribute 'shape'
FAILED mantidimaging/core/gpu/test/gpu_test.py::GPUTest::test_image_slicing_works - AttributeError: 'ImageStack' object has no attribute 'shape'
FAILED mantidimaging/core/gpu/test/gpu_test.py::GPUTest::test_array_input_unchanged_when_gpu_runs_out_of_memory - AttributeError: 'ImageStack' object has no attribute 'shape'
```

### Steps To Reproduce

On a machine with a GPU
`make test`
or just a specific test
`pytest -k test_executed_with_nan_1_GPU`

### Expected Behaviour

All run and pass

### Current Behaviour

Several tests fail

Current main

### Failure Logs
```
data = <mantidimaging.core.data.imagestack.ImageStack object at 0x7419f92fa290>, size = 3, mode = 'reflect', progress = None

    def _execute_gpu(data, size, mode, progress=None):
        log = getLogger(__name__)
>       progress = Progress.ensure_instance(progress, num_steps=data.shape[0], task_name="Median filter GPU")
E       AttributeError: 'ImageStack' object has no attribute 'shape'

```

**Comment by samtygier-stfc** [comment]
Bisected with
```
git bisect start main release-2.7.0
git bisect run pytest -k test_executed_with_nan_1_GPU
```
gives 0b0946307951640674c038c7b3e1828b5d4e5d71 is the first bad commit. So probably due to change
` _execute_gpu(data.data, size, mode, progress)` to `_execute_gpu(data, size, mode, progress=None)` in 

https://github.com/mantidproject/mantidimaging/pull/2088/files
